trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(Build.ArtifactStagingDirectory)/publish'
  runtimeIdentifier: 'linux-x64' # Targeting Linux

steps:
# Step 1: Check out the repo
- checkout: self

# Step 2: Restore NuGet packages
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Step 3: Build and Publish the project as a standalone Linux executable
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(outputDirectory) --runtime $(runtimeIdentifier) --self-contained true /p:PublishSingleFile=true'

# Optional: List build artifacts for verification
- bash: |
    ls -la $(outputDirectory)
  displayName: 'List build artifacts'

# Step 4: Upload to FTP
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://$(FTP_HOST)'
    username: '$(FTP_USER)'
    password: '$(FTP_PASS)'
    rootDirectory: '$(outputDirectory)'
    remoteDirectory: '/home/$(FTP_USER)/ftp'
    clean: false
    cleanContents: false
    preservePaths: true
    trustSSL: false

# Optional: Clean up the directory after upload
- bash: |
    rm -rf $(outputDirectory)
  displayName: 'Clean up published files'
